Detect git before run dots-install

diff --git a/bin/dots-install b/bin/dots-install
--- a/bin/dots-install
+++ b/bin/dots-install
@@ -1,16 +1,25 @@
 #!/bin/sh
 
+git --version > /dev/null
+if [ $? -ne 0 ]; then
+  echo 'abort: please install git'
+  exit 1;
+fi
+
 git clone --bare git@github.com:teohm/dots.git $HOME/.dots
+
 function dots {
    git --git-dir=$HOME/.dots/ --work-tree=$HOME $@
 }
-mkdir -p .dots-backup
+
 dots checkout
 if [ $? = 0 ]; then
   echo "Checked out dot files.";
-  else
-    echo "Backing up pre-existing dot files.";
-    dots checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dots-backup/{}
+else
+  echo "Backing up pre-existing dot files.";
+  mkdir $HOME/.dots-backup
+  dots checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dots-backup/{}
 fi;
+
 dots checkout
 dots config status.showUntrackedFiles no
